name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Deployment success! ✅"
        SLACK_MESSAGE: |
          `${{ github.event.deployment.ref }}` was successfully deployed to `${{ github.event.deployment.environment }}`!
            Click <${{ github.event.deployment_status.target_url }}|here> to access the deployed version or <${{ github.event.repository.html_url }}/commit/${{ github.event.deployment.sha }}/checks|here> to see the logs.:  

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Send Slack notification
      uses: bryan-nice/slack-notification@master
      if: failure()
      env:
        SLACK_TITLE: "Build failed! 🔴"
        SLACK_MESSAGE: |
          Check the CI logs <https://github.com/martapanc/ItalianFiscalCodeCalculatorApp/actions/runs/136097932|here>.
