name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: "🚧"
        
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build success
      uses: bryan-nice/slack-notification@master
      if: success()
      env:
        SLACK_TITLE: "Build succeeded! ✅"
        SLACK_MESSAGE: |
          Check the CI logs <https://github.com/martapanc/ItalianFiscalCodeCalculatorApp/actions|here>.
    
    - name: Build failure
      uses: bryan-nice/slack-notification@master
      if: failure()
      env:
        SLACK_TITLE: "Build failed! 🔴"
        SLACK_MESSAGE: |
          Check the CI logs <https://github.com/martapanc/ItalianFiscalCodeCalculatorApp/actions|here>.

